### ISSUE TITLE
CUDNN Error calling krRecvPost->setArgs in HyPerConn.cpp with cuda 7.5 and cudnn 7.0 v4

### ISSUE THREAD

**Issue by wshainin** [PetaVision/OpenPV#23]
While running [HyPerLCA_PASCAL_S1_128_S2_256_S3_512_DCA.params.txt](https://github.com/PetaVision/OpenPV/files/92647/HyPerLCA_PASCAL_S1_128_S2_256_S3_512_DCA.params.txt) with cuda, cudnn, mpi, and threads, execution fails with the following error:
'CUDNN Set convolution tensor descriptor error: CUDNN_STATUS_BAD_PARAM'

I've seen this same error on two different machines, one with cuda 7.5 cudnn 7.0 v4, and one with cuda 6.5 and cudnn 7.0. Gar is currently running this params file with an older executable created on Dec 21st (not sure which cud(a/nn) libraries it's linked to).

The issue seems to be in initializing the connection S2DeconS3ToS1DeconS3 during the call 'krRecvPost->setArgs' in 'HyPerConn::allocateReceivePostKernel()' on line 2360 of HyPerConn.cpp, after a few other connections have been allocated.

**Comment by slundqui** [comment]
It looks like the error is originating from setting up the CuDNN convolution descriptor call. Namely, the call to create the convolution descriptor is so:

   status = cudnnSetConvolution2dDescriptor(convDescriptor,
      diffY,
      diffX,  //zero-padding height and width
      strideY, //Vertical filter stride
      strideX, //Horizontal filter stride
      1, 1, //upscale the input in x/y direction
      CUDNN_CONVOLUTION);

Here, the problem lies with diffY and diffX. Our pre margins may be bigger than what is required for the connection calling the convolution patch. For example, the current connection needs a margin of size 2 from the pre, but another connection requires the same pre layer to have a margin of 4. This means that in order to get the pre data into a format that CuDNN is looking for, we need to crop a margin of 2 off of the pre layer to match the post dimensions after a convolution, or to crop the post layer after doing a convolution. Previously, I was passing a negative number for the zero-padding height and width, which just seemed to work, but it looks as if the new version of CuDNN has disallowed this.

**Comment by garkenyon** [comment]
my understanding of this particular connection is that it does indeed involve a pre layer (S2DeconS3) that makes more than one connection to other layers.  Normally, in LCA, a Recon layer would only connect to an error layer with an identConn (margin == 0).  However, since this is DCA, the "Decon" layer is used to reconstruct S1 activity (and eventually pixels, where the competition occurs).  The Recon connection would be one to many and would certainly involve a margin different from 0.  However, there is only one margin that's relevant for the GPU, so I guess I'm not sure why this wouldn't work, since we're not implementing the identConn on the GPU.  A work around might be to simply not implement this connection on the GPU, but that's kinda unsatisfying.  Another possibly relevant point.  Normally, for LCA, we implement transposeConns on GPUs, and we receive from the post perspective, for which the margin should be zero.  All patches are full sized from the post perspective.  I have to check but I think that's how this connection is being implemented.  Why should margins even matter for full sized patches?

**Comment by slundqui** [comment]
The basic discrepancy is the memory transfer from the CPU to the GPU. As
the datastore is stored in extended space, transferring the buffer to the
GPU is trivial if the GPU memory buffer is of the same size. However, when
these buffers differ in size, as in the case if when the margins is bigger
due to another connection, we need to do something to go from the CPU sized
buffer that other connections need to the GPU sized buffer. I currently
have a fix in the works that should crop the input buffer to the correct
size when copying from CPU to GPU, but am currently crashing machines
whenever I run system tests (not due to the fix: the current master branch
is also doing this)

As for the post patches requiring a margin, there exists a dependency
somewhere that expects margins to be extended as if it was from the pre (if
I recall correctly, it was probably the function that returns the start of
the patch in pre space given a post index or vice versa).

**Comment by slundqui** [comment]
Fixed in commit 2db29a9d088bd20efa84608a61227417711512b4.
