### ISSUE TITLE
ioParam triggerBahavior in HyPerLayer / HyPerLCALayer not recognized

### ISSUE THREAD

**Issue by mantier** [PetaVision/OpenPV#242]
#### Regarding the bug
There is a bug in the HyPerLayer which leads to failure of the triggerBahavior setting. I wanted to create a zero layer to reset the LCA layer for each image presentation. This works in an old 2016 build but unfortunately not with the current build. When setting `triggerBahavior = "resetStateOnTrigger";` I get `WARN Using default value "updateOnlyOnTrigger" for string parameter "triggerBehavior" in group "V1"` in my log file. 

I have already checked that the bug is not in *HyPerLayer.cpp*, line 792. `triggerBehaviorType = RESETSTATE_TRIGGER;` is set correcty. Unfortunately, PetaVision code structure still remains too unclear to me to debug further. 

Find attached a copy of the params file and the log file:
[run.log.txt](https://github.com/PetaVision/OpenPV/files/1292878/run.log.txt)
[LCA_Cifar_own.lua.txt](https://github.com/PetaVision/OpenPV/files/1292874/LCA_Cifar_own.lua.txt)
[LCA_Cifar_own.params.txt](https://github.com/PetaVision/OpenPV/files/1292875/LCA_Cifar_own.params.txt)

#### Regarding PetaVision in general
It seems to not be so easy to [reach out to someone via GitHub](https://stackoverflow.com/questions/12686545/how-to-leave-a-message-for-a-github-com-user) so I add my comments here. 

I am very pleased to see that PetaVision is still under active development. We have been using it for some time now and some [Bachelor-Theses](http://www.cog.uni-tuebingen.de/research/finished-projects.html) were made possible using PetaVision (search for sparse coding). 
It didn't miss my attention though that development is less active in the meantime. So, could you say anything about what you are planning for the future?

I could offer to register as a developer if this is desired. As suggested above, the inner structure of PetaVision is still confusing to me. But I could at least help with some documentation and analysis tools.

**Comment by garkenyon** [comment]
looking at LCA_Cifar_own.lua.txt file you attached, there appears to be a spelling error:

triggerBahavior should be triggerBehavior:

However, I'm confused about your intent.  "ZeroLayer" is a HyPerLCALayer that uses an initVType method "UniformRandomV" and also sets triggerLayerName to "InputLayer".  it appears that you are expecting ZeroLayer to reinitialize its state to new random value for each input.  This is not what happens however.  The initVType method is only run once during initialization.  You are getting the same random values for each input.

Our philosophy has been that in order to keep the code base as uncluttered as possible, we have not implemented a separate noise layer for the purpose of generating random values on each update of the layer.  Rather, we use python/octave/matlab to make a pvp file that contains noise with the desired properties and read in that pvp file using PvpLayer.  Note that a HyPerLCALayer does NOT have to point to another HyPerLCALayer for it's reset values.  If you want to reset the values of the HyPerLCALayer to zero upon each image flip, for example, you should point the HyPerLCALayer to a ConstantLayer with initVType set to ZeroV.

**Comment by peteschultz** [comment]
As Gar pointed out, you received the "Using default value" warnings because of a typo in the parameter name. The code also scans the list of parameters and issues a warning if any paramenters went unread, in order to help track down typos like this. I notice that your run.log.txt did not have any such warnings, which would have been,

WARN Parameter group "V1": parameter "triggerBahavior" has not been read.
WARN Parameter group "ZeroLayer": parameter "triggerBahavior" has not been read.

Did you send only a portion of the log file, or do these warnings not appear when you do a run?

**Comment by mantier** [comment]
Well.... yes I copy-pasted this typo throughout all my lua-scripts, things are working now.. Also, when debugging through *HyPerLayer.cpp*, of course `triggerBehaviorType=UPDATEONLY_TRIGGER` is set.  Next time I shoud sleep over sth before posting it... 
The run.log.txt is complete though, I checked again today. Built source is the newest pull from the master branch.

Thanks for the extended response,. I think I would have fallen into that pitfall. 
It was nagging me that activations are initialized from the previous image presentation even though I do not present consecutive frames. I wanted to initialize with a constant value per presentation but 'on the fly' (meaning not thought through) I came up with the Idea that some noise might encourage competition and stability amongst redundand kernels. Then again I thought the opposite effect could happen because when both are initialized equally, the better fitting kernel would win from the beginning. Also, I was thinking noise might help generally less active kernels to get a pick from time to time and to find their place. 

Any thoughts on how to best initialize non-consecutive data per presentation?

**Comment by garkenyon** [comment]
we typically use ImageLayer::batchMethod = "random" to ensure that a given image is preceded by a different initial condition each time it's presented

**Comment by mantier** [comment]
Thank you very much for your help. 
I'll close the thread then (except you want to investigate further why the log file does not have the expected warnings).

**Comment by peteschultz** [comment]
Sorry for the delayed response, but I tried running with your params file, and I did get the "has not been read" warnings. The attached run.log.txt is the entire rank-zero log file, and warnings.txt is the part of the log that contains all the warnings. 
[run.log.txt](https://github.com/PetaVision/OpenPV/files/1311340/run.log.txt)
[warnings.txt](https://github.com/PetaVision/OpenPV/files/1311342/warnings.txt)

So I'm puzzled why you didn't get these warnings. If you'd like to look into this further, please feel free to reopen the issue; otherwise I'll keep it closed.

**Comment by mantier** [comment]
Sure, I hope I can help. This week I don't have time. I can do sth next week.

**Comment by peteschultz** [comment]
Thanks; next week might be better here too.

Looking a little more closely at the run.log files you and I got, I see that these two files are essentially the same right up until your last line,
`HyPerLCALayer "ZeroLayer": selfInteract flag is true`
where mine continues with the line
`WARN Using default value of nullptr for string parameter "adaptiveTimeScaleProbe" in group "ZeroLayer"`
and then continues with setting nfp in connections, margin widths in layers, etc.

The selfInteract and adaptiveTimeScaleProbe paramaters are read one right after the other, in src/layer/HyPerLCALayer.cpp, lines 75 and 76.

So either your run somehow died right between these two lines, or some file system hiccup caused the output of the process to be disconnected from the run.log file. I think I remember that we had issues with the latter on an older filesystem - that seems to be a file server issue as opposed to a PetaVision issue. Although it's unusual that it would happen right at the beginning of the run.

**Comment by mantier** [comment]
Finally found some time. 

I think you are on the right track with the latter. The run definitely does not die, output files like L1-/ L2-error files are constantly written. But PetaVision completely runs from a ntfs partition (Windows installed on the same pc). 

The code runs through  `HyPerLCALayer::ioParamsFillGroup(enum ParamsIOFlag ioFlag)` without any problems. Is it normal that this function is called six times? the `name` variable in `ioParam_adaptiveTimeScaleProbe` is _ZeroLayer_ and _V1_ three times each. Other than that I do not see anything peculiar.

Where can I go on debugging?

**Comment by peteschultz** [comment]
Yes, for each layer it calls ioParamsFillGroup the following times:
when reading the params file (ioFlag is set to PARAMS_IO_READ);
when writing the CIFAR_Tutorial.params file to the output directory (ioFlag==PARAMS_IO_WRITE);
and when writing the pv.params file to a checkpoint (ioFlag==PARAMS_IO_WRITE again).

In your run, the log file would have stopped logging during the first call with name==ZeroLayer, when ioFlag was PARAMS_IO_READ. Inside the call to ioParam_adaptiveTimeScaleProbe, the call to the ioParamString method should reach line 1438 of src/io/Params.cpp. The WarnLog().printf call there should send it to line 396 of PVLog.hpp, where it should reach the << operator in line 405, with output_string having the value `Using default value of nullptr for string parameter "adaptiveTimeScaleProbe" in group "ZeroLayer"`.

Does the log file cut off at the same point each time you run?

**Comment by mantier** [comment]
Yes, there has not been one time the log file cut off at a different point.

Following the steps you outlined the variable `fmt` in `printf` is _0x6d48f8 Using default value of nullptr for string parameter \"%s\" in group \"%s\"\n"_ but `chars_printed = vsnprintf(output_string, chars_needed, fmt, args2);` in line 404 is empty, even though `chars_printed` is set to _98_ (`chars_needed` is _99_). 

Somehow I can never read the char `output_string` in my debugger. Not before the cut and not after. I always get _output_string[0]_. Any idea why that is? (Does not seem to have anything to do with the bug, because this is always the case) 

I found out vsnprintf is part of stdio.h and I understand how the `printf` function in PVLog.hpp works. I can confirm that, in PVParams.cpp,  `paramName` is _0x6f0d66 "adaptiveTimeScaleProbe"_ and `groupName` is _0x9aad20 "ZeroLayer"_. However, I do not know how to read these values from the `args1`, `args2`.

Having these things said, I think the problem is narrowed down a bit. However, I have no clue why the vsnprintf could fail at this point and, obviously, on all consecutive instances. I can confirm that I can read out all missing messages before the cut and from that point on from the variable `fmt` when setting a debug point on the `printf()` function.

I also set a debug point at the logging immediately before the cut: HyperLCALayer.cpp, line 85, `ioParam_selfInteract`, nothing funny there. But I recognize a lot is being logged when calling `ioParam_selfInteract` (line 253 to 285 in the log file, beginning with _Petavision initialized at..._ and ending with _HyPerLCALayer "ZeroLayer": selfInteract flag is true_, but I fail to find the corresponding code.

I think this is a good point to ask for ideas where to take a closer look.

**Comment by peteschultz** [comment]
I'm not sure why your debugger wouldn't display output_string. When I try using gdb, I get

`(gdb) print output_string`
`$7 = "Using default value of nullptr for string parameter \"adaptiveTimeScaleProbe\" in group \"ZeroLayer\"\n"`

It might have something to do with output_string being declared as an array as opposed a pointer. Perhaps changing the declaration from
`char output_string[chars_needed];`
to
`char *output_string = malloc(chars_needed)`
would allow the debugger to see the value? Of course, changing the code this way might also change the behavior of the bug.

I'm not sure how to inspect objects of type va_list, like args1 and args2; and it probably varies from compiler to compiler.

I'd like to be sure that output_string and _stream have the correct values when you reach line 405. The values of `&_stream`, `outputLogFileStream.mStream`, and `errorLogFileStream.mStream` should be the same. The values of `outputLogFileStream.mStream` and `errorLogFileStream.mstream` should be set very early in the program by setLogFile in src/utils/PVLog.cpp, line 86; and then not change after that. The problem though, is that if something internal to the stream pointed to by these variables gets clobbered, the debugger probably can't inspect the internal structure easily.

Another idea would be to check the values of `_stream.fail()` and `_stream.bad()` before and line 405.

ioParam_selfInteract only produces the line `HyPerLCALayer "ZeroLayer": selfInteract flag is true`. If the log file was 252 lines on entering ioParam_selfInteract and 285 lines long on returning from it, that would have to be from the OS buffering the log file.

**Comment by mantier** [comment]
I think I've found it: warnings are not being flushed. I added `WarnLog().flush()` in line 1443 of PVParams.cpp. Now the line _WARN Using default value of nullptr for string parameter "adaptiveTimeScaleProbe" in group "ZeroLayer"_ is being written to my log file (might be the wrong position to flush though, the last line is _WARN_ without anything else, the line gets filled up on the next warning instance). Maybe flushing is not necessery for ext4 but for ntfs?

I found out all `action_parameter*` get flushed in PVParams.cpp, immediately after being sent to the `_stream` object. I set a debug point on each and every `flush()` inside PVParams.cpp. All `action_parameter_*` get flushed here, corresponding to the according appearance in the file. But no flush is ever reached after the last action parameter (beginning with _PetaVision initialized at..._). `flush()` is called for `getOutputStream().flush()` and all `InfoLog().flush()`, but never for `ErrorLog()` or `WarnLog()`.


For completeness sake, additional things you asked for:
- I can read the variable now. I use KDevelop and it seems to have an issue displaying the variable content but using the console I get 
`print output_string`
`$6 = 0x7fffffffdd40 "Using default value of nullptr for string parameter \"adaptiveTimeScaleProbe\" in group \"ZeroLayer\"\n"`.

- Variables `&_stream`, `outputLogFileStream.mStream`, and `errorLogFileStream.mStream` get assigned with _0x998140_ in PVLog.cpp, line 86 and do not change that value at any further point, neither before nor after the cut. 
`_stream.fail()` and `_stream.bad()` both keep returning false before as well as after the cut.

**Comment by peteschultz** [comment]
Thank you for tracking that down; you're right that the stream is not getting flushed. The 'selfInteract flag is true' messages get flushed because their print-statements end in std::endl. After that, the stream never gets flushed again until the end of the run, when the timing information gets printed. But I assume that you interrupted the run once you saw that the triggering wasn't working as expected. I saw the lines you weren't seeing because I had changed the stopTime parameter to a very small value, so my run did go to completion.

As for where to put the flush() commands, I think the WarnLog should automatically flush before and after a warning; that way, a flush command doesn't have to inserted with every warning. The extra line containing only WARN was generated because the WarnLog() expression in `WarnLog.flush()` instantiates a WarnLog object, and the WARN is printed during its constructor. Having the flush commands happen inside the WarnLog implementation also avoids the extra instantiation of a WarnLog object.

I've put a branch called `logfile-flush` that contains these changes. Could you check this branch to make sure that it fixes the log file issue for you?

**Comment by mantier** [comment]
Great, I am glad I could help.

there is a little typo: PVLog.hpp, line 346: `logType::flushOutputStream()` -> `LogType::flushOutputStream()`

I was thinking: maybe, just to be safe, it would be a good idea to evoke a final flush on SIGTERM? At least for me the usual workflow is to run the program with a very high stopTime value and end it whenever I wish. Also a logging message (like _received SIGTERM at time xyz_) would be nice. (A little additional feature request if not too laborious: writing a last checkpoint.)

Isn't it a bit incomprehensive that `InfoLog` (and I do not know the other log types) is still being flushed like before? Also it is error prune to the logging problem. E.g. `printInitMessage()`, line 224 in PV_Init.cpp is never being flushed. You never know whether a message is the last message for some time. 

Of couse, these are being flushed now by warnings. See attached my log file:
[run.log.txt](https://github.com/PetaVision/OpenPV/files/1344256/run.log.txt)

**Comment by peteschultz** [comment]
The idea behind not automatically flushing InfoLog is that it's like stdout, which is typically buffered; while WarnLog and ErrorLog are like stderr, which is not buffered. It makes sense, though, to have the end of initialization and the progress message (e.g. "time==xyz", followed by the wallclock time) flush the output.

We do have a way of generating an immediate checkpoint in response to the SIGUSR1 signal. It continues the run once the checkpoint is written, but once the checkpoint is written you could stop it as before. The SIGUSR1 feature is described in a blog post at <http://petavision.github.io/jekyll/update/2015/07/07/generating-an-immediate-checkpoint.html> (unfortunately, we haven't systematically been using our blog or wiki, but the sigusr1 feature is there).

For the idea of having SIGTERM cause a checkpoint and then quit, we'd like to discuss it with our other team members before deciding whether to put it into the repository.

I'll make the changes to flush at the end of initialization, when the "time==xyz" progress message is printed, and in response to a SIGUSR1-generated checkpoint; and then close the issue.

**Comment by mantier** [comment]
Thx for the SIGUSR1 tip, that's a feature I am going to use.
