### ISSUE TITLE
internal state not loaded onto GPU when initialized from file 

### ISSUE THREAD

**Issue by garkenyon** [PetaVision/OpenPV#27]
there is a bug in PetaVision such that reading a layer from a file does not load that layer's internal state onto the GPU.  Since it can take 1000's of time step to reach a stable solution from a random or zero initial state, the ability to read an internal state from a file is an important capability.

**Comment by peteschultz** [comment]
I was unable to reproduce this bug.  I started with GPUSystemTest/input/HyPerLCAGpuTest.params.  I tried a run where the HyPerLCALayers were initialized using InitVFromFile, and a run where the HyPerLCALayers were initialized using initializeFromCheckpointFlag.  In both cases, the comparison with GPU and CPU were roundoff-error size, not the size you'd expect if the GPU's initial state was different from the CPU's.

**Comment by garkenyon** [comment]
if you try starting with a trained dictionary and try to read from a final checkpoint and simply look at the HyPerCol_timescales.txt file, you'll see from the energyProbe that the energy (timeScaleTrue) remains constant for hundreds of time steps.  On the other hand, if you boot from the final checkpoint, the energy starts off at the expected value and begins to fall immediately.  The above GPU test seems like it should work but you have to be careful to test the LCA layer that has updateGpu = true.

**Comment by peteschultz** [comment]
This appears not to be a GPU vs CPU bug.  If an LCA module's V1 layer uses InitVFromFile with a file from an earlier checkpoint, the system indeed fails to recover its original state.  However, it fails the same way whether the V1 layer has updateGpu set to true or false.

If the residual and reconstruction layers also use InitVFromFile from the same checkpoint, however, the system does recover its original state---but only if all three layers have InitVFromFile.  As Gar points out, this is puzzling because the reconstruction is an ANNLayer and is recomputed each timestep, without needing the state at the previous timestep.

**Comment by peteschultz** [comment]
This is not a bug, but instead reflects the fact that with the usual choice of phases, the error layer's update at time t=n+1 depends on the recon layer's status at time t=n.  If the recon layer is not initialized along with V1, the error at timestep 1 will not agree with the earlier run that V1 was initialized from.  This then affects the update of V1, and the difference continues.

Had the phases been chosen with recon < error < V1, then only the V1 layer needs to be reinitialized.
