### ISSUE TITLE
Projects directory in OpenPV

### ISSUE THREAD

**Issue by slundqui** [PetaVision/OpenPV#31]
I know we've talked about this several times before, but I'm adding this here to keep this issue centralized, as most of this discussion is in other issues or email correspondence. Should we start removing various project directories out of the main repository in favor of having individual repos that simply link to the pv-core library? The one exception to this would be projects that have led to publications, but I know that I personally have to extract relevant parameter files and scripts out of the DepthLCA project directory.

**Comment by garkenyon** [comment]
I agree.  We need to clean up the analysis files in pv-core as well.  Even projects referenced by publications should be in separate repositories I think.  Exceptions could be made for projects that add general capability but for some reason we don't want to include in pv-core.  For example, if there were specialized classes that were need from some general capability (i.e. linking to openCV, not that we currently do that, but if we did...), that might be part of the central github distribution but not included in pv-core.

**Comment by dpaiton** [comment]
I agree with Gar - all projects should be in a separate repository. I have created a PetaVision/Projects repository. Owners of projects that currently live in OpenPV/projects should start to migrate their projects over. During the migration, owners should also verify that the projects sill run. If they don't run, projects should be moved to an 'deprecated projects' folder in the PetaVision/Projects directory.

**Comment by slundqui** [comment]
I was under the assumption that each individual projects should be a separate repositories, maintained by the owner of the repo. Are we moving all projects to a shared repository?

**Comment by dpaiton** [comment]
I created a fork of the Projects repository. Within that fork I created a folder for a project that @wshainin and I are working on. I made a pull request to the PetaVision/Projects folder, which I don't intend to merge until the project is in a completed (at least to a point) state.

**Comment by slundqui** [comment]
You misunderstood what I meant. Right now, my DepthLCA projects repository is not under the PV repo group at all; rather, it's a completely separate repository in my github. So my question is are we moving all projects to a single repository (the one that Dylan just made), or are we de-centralizing the projects such that there is a separate repo per project?

**Comment by dpaiton** [comment]
Oh, I see, my fault. I did misunderstand you. I think the solution I implemented is best. Especially for projects that have reached milestones (such as publication) and are ready to be picked up by future researchers.

**Comment by wshainin** [comment]
I think the original idea for having a projects folder was that adding a project to cmake was simple. If we move it out we should either decide that it's up to the user to configure the project for compilation, or establish some other method. It does seem a little clunky, both having to pull all projects to use one, and to have all the projects (stale, obsolete, broken) in the core repository.

**Comment by slundqui** [comment]
I disagree. The reason why we're moving the projects directory out of the core repo is to keep the core repo clean. While having a shared repo is a step in the right direction, I can foresee this new shared projects repo getting just as cluttered as before. Furthermore, as @wshainin points out, in order to use one project, we need to pull all projects.

**Comment by dpaiton** [comment]
Yes, I agree that is a problem. However, the alternative of keeping all projects on individual repositories goes against Gar's wishes to have all PetaVision related work in one place. I have proposed using the Fork/pull-request workflow in order to prevent people from having to download scratch projects. However, it would be the case that if someone wanted to download a finished project (BIDS, for example) they would have to download all of the finished projects. 

I see pros/cons to both sides. @garkenyon - do you have an opinion on the matter?

**Comment by peteschultz** [comment]
I also think that each individual project should be its own repository, for the reason that each project is typically independent from all the other projects.  I believe that Gar's principal concern about keeping PetaVision in one place is satisfied if (1) the default location for a project repository is inside the PetaVision organization, and (2) the project repository does not contain its own copy of the core PetaVision library, but instead links to the OpenPV repository.

**Comment by dpaiton** [comment]
Alright, that makes sense. One negative side-effect of what @peteschultz  is proposing is the PetaVision organization will become cluttered over time with projects. Ideally we want the github.com/petavision url to point to a clean page so that potential users can easily see what we think is important, such as OpenPV. If all of the current and future projects go into the root PetaVision organization, OpenPV will just be one among many options. Other popular repositories on GitHub seem to only post libraries to their organization. Applications that use said libraries are hosted elsewhere.

**Comment by slundqui** [comment]
I would like to point out that I currently have my DepthLCA repo in my own github account as opposed to the PetaVision organization to avoid this problem.

**Comment by peteschultz** [comment]
It's true that OpenPV should have top billing.  Currently there are four repositories listed on github.com/PetaVision, with OpenPV appearing second, and even that's unfortunate.  [petavision.github.io](https://petavision.github.io) would make a better front door than github.com/PetaVision, since we control the the one but not (at least as far as I can find) the other.

@dpaiton, when you said, "hosted elsewhere", did you mean on a different account as @slundqui mentioned, or a different site?

**Comment by dpaiton** [comment]
I agree with @peteschultz that the petavision.github.io site should be our main page, rather than the PetaVision organization page. That being said, I think my point is still valid. Our organization page should hold libraries and tools, not individual projects. By "hosted elsewhere" I mean on a different account as @slundqui mentioned. That is also how I'm currently hosting the [Sparse Sampling](https://github.com/dpaiton/Projects/tree/master/SparseSampling) project that I'm working on with Will. If you look there you can see that it still references the PetaVision/Projects folder that I created (via a Fork) but does not actually live in that folder. Once the project results in publication or we consider it sufficiently complete, I think it makes sense to move it over to the PetaVision/Projects folder where it can live out its life as a successful use of PetaVision.

**Comment by garkenyon** [comment]
no easy answer here.  no solution really satisfies all the constraints.  as @peteschultz notes, if someone is actually being paid to develop PetaVision, their work should be entirely contained within the PetaVision organization.  I believe that IP rules basically require this.  Hopefully someone can look into the IP issue more fully.  On sourceforge, PetaVision was under an eclipse public license.  I assume the same license still applies.  I really should know these things.  Does the eclipse public license apply to all projects in the PetaVision organization?  It should and I need to make sure that's true if it isn't true already.  As far as the resolution of the immediate issue, I have to insist that all work being funded for developing PetaVision be in the PetaVision organization and covered by the eclipse public license.  I cannot approve of keeping work funding by PetaVision in a separate individually owned repository.  Of course, for anyone not being paid to develop PetaVision, it's their call as to where they want to keep their work.  The clutter issue is important.  I think we have to remain vigilant to make sure that projects in the PetaVision organization are active and not broken.

**Comment by dpaiton** [comment]
Given @garkenyon's response, I would advocate for putting projects into a 'projects' folder in the PetaVision organization root. The downside is that whenever someone wants to work on a project they have to pull down all of the projects. The upside is that the PetaVision organization root stays clean and easy to parse. I believe the upside outweighs the downside. Ultimately I think it'll have to be @garkenyon who settles this debate, or we can flip a coin. :8ball:

**Comment by garkenyon** [comment]
the single folder vs many folders issue is impossible to resolve.  it really is a coin flip.  maybe we could have a sandbox folder that contained lots of nutty ideas and separate folders for more stable projects that deserve to stand on their own.  I really don't know.  

Also, I may have misspoke above.  Someone who is not being paid to develop PetaVision probably needs to be careful about putting their IP into the PetaVision organization because that might imply that such work is covered by the PetaVision public license when in fact that IP probably belongs to the organization that is paying that individual.   Thus, it makes sense for someone not being paid to develop PetaVision to maintain their own individual repository, I think.  These IP issues get very convoluted.  If someone is a student at institution A and is being paid to develop PetaVision, who does the IP generated by that student actually belong to?  In most cases, I think being paid by an institution involves signing an IP agreement, but I suspect there could be competing IP agreements that a student might be asked to sign...

**Comment by peteschultz** [comment]
It looks like GitHub steers people toward establishing licenses at the repository level; an account with six different repositories could use six different licenses, one for each.  There doesn't seem to be a way to post a license so that it covers all repositories in the organization.

OpenPV has a license file, the Eclipse Public License, in its top directory (as well as in several subdirectories, a legacy from when those subdirectories were separate repositories).  I don't think there's an implication that a license in OpenPV would extend to other repositories in the organization. So I think we'd need to put the license file in the Projects repository, if we stick with that; or put the license in each of the individual project repositories if we go that route.

**Comment by slundqui** [comment]
I have moved my DepthLCA toolbox into the Projects repository within the PetaVision organization.

**Comment by wshainin** [comment]
There is no longer a projects directory in the develop branch. All projects are now in the Projects repository under the PetaVision group.
